version: '3.1'

services:

  plant-server-0:
    image: plant-simulation-service:1.0
    restart: always
    networks:
      - proiect_default
    environment:
     - PLANT_SERVICE_NAME=plant-0
     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
     - PLANT_SERVICE_PORT=9000
     - PLANT_REGISTRY_URL=http://discovery-server:8761
     - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/plant-0

  plant-server-1:
    image: plant-simulation-service:1.0
    restart: always
    networks:
      - proiect_default
    environment:
     - PLANT_SERVICE_NAME=plant-1
     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
     - PLANT_SERVICE_PORT=9001
     - PLANT_REGISTRY_URL=http://discovery-server:8761
     - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/plant-1

     




networks:
  proiect_default:
    name: proiect_default
    driver: bridge
  
