server:
    port: 9191
    error:
      include-binding-errors: always
      include-message: always

spring:
   data:
      mongodb:
        datbase: users
        uri: mongodb://localhost:27017/users
   main:
      web-application-type: reactive
   application:
       name: API-GATEWAY

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        hostname: localhost