# Use root/example as user/password credentials
version: '3.1'

services:

  discovery-server:
    image: discovery-service:1.0
    restart: always
    networks:
      - proiect_default
    environment:
      - API_GATEWAY_URL=http://api-gateway:9191
      - SPRING_DATASOURCE_URL=jdbc:mysql://root:example@db:3306/plants?createDatabaseIfNotExist=true
    ports:
      - 8761:8761

networks:
  proiect_default:
    name: proiect_default
    driver: bridge
  