# Use root/example as user/password credentials
version: '3.1'

services:
  
  api-gateway:
    image: api-gateway-service:1.0
    restart: always
    networks:
      - proiect_default
    ports:
      - 9191:9191
    environment:
    - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/users
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
    - SPRING_CLOUD_GATEWAY_ROUTES[0]_URI=http://plant-server-0:9000
    - SPRING_CLOUD_GATEWAY_ROUTES[0]_ID=plant-0
    - SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]=Path=/api/plant-0/plant_status/**
    - SPRING_CLOUD_GATEWAY_ROUTES[1]_URI=http://plant-server-1:9001
    - SPRING_CLOUD_GATEWAY_ROUTES[1]_ID=plant-1
    - SPRING_CLOUD_GATEWAY_ROUTES[1]_PREDICATES[0]=Path=/api/plant-1/plant_status/**
    - SPRING_CLOUD_GATEWAY_ROUTES[2]_URI=http://plant-server-2:9002
    - SPRING_CLOUD_GATEWAY_ROUTES[2]_ID=plant-2
    - SPRING_CLOUD_GATEWAY_ROUTES[2]_PREDICATES[0]=Path=/api/plant-2/plant_status/**
    - SPRING_CLOUD_GATEWAY_ROUTES[3]_URI=http://discovery-server:8761
    - SPRING_CLOUD_GATEWAY_ROUTES[3]_ID=discovery-server
    - SPRING_CLOUD_GATEWAY_ROUTES[3]_PREDICATES[0]=Path=/api/v1/plant/**


networks:
  proiect_default:
    name: proiect_default
    driver: bridge
  